/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AlertsRouteImport } from "./routes/alerts"
import { Route as BillsRouteImport } from "./routes/bills"
import { Route as ManageRouteImport } from "./routes/manage"
import { Route as ProfileRouteImport } from "./routes/profile"
import { Route as ReportsRouteImport } from "./routes/reports"
import { Route as OutletOutletIdRouteImport } from "./routes/outlet.$outletId"
import { Route as PcOutletIdRouteImport } from "./routes/pc.$outletId"
import { Route as ReportReportIdRouteImport } from "./routes/report.$reportId"
import { Route as SummaryDateRouteImport } from "./routes/summary.$date"
import { Route as TablesOutletIdRouteImport } from "./routes/tables.$outletId"
import { Route as BillOutletIdBillIdRouteImport } from "./routes/bill.$outletId.$billId"
import { Route as ManageMenuOutletIdRouteImport } from "./routes/manage_.menu.$outletId"
import { Route as ManageStaffOutletIdRouteImport } from "./routes/manage_.staff.$outletId"
import { Route as ManageStockOutletIdRouteImport } from "./routes/manage_.stock.$outletId"
import { Route as ManageTablesOutletIdRouteImport } from "./routes/manage_.tables.$outletId"
import { Route as ManageSettingsOutletIdSectionRouteImport } from "./routes/manage_.settings.$outletId.$section"
import { Route as ManageStaffOutletIdStaffIdRouteImport } from "./routes/manage_.staff.$outletId_.$staffId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: "/alerts",
  path: "/alerts",
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: "/bills",
  path: "/bills",
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: "/manage",
  path: "/manage",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => rootRouteImport,
} as any)
const OutletOutletIdRoute = OutletOutletIdRouteImport.update({
  id: "/outlet/$outletId",
  path: "/outlet/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const PcOutletIdRoute = PcOutletIdRouteImport.update({
  id: "/pc/$outletId",
  path: "/pc/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReportIdRoute = ReportReportIdRouteImport.update({
  id: "/report/$reportId",
  path: "/report/$reportId",
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryDateRoute = SummaryDateRouteImport.update({
  id: "/summary/$date",
  path: "/summary/$date",
  getParentRoute: () => rootRouteImport,
} as any)
const TablesOutletIdRoute = TablesOutletIdRouteImport.update({
  id: "/tables/$outletId",
  path: "/tables/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const BillOutletIdBillIdRoute = BillOutletIdBillIdRouteImport.update({
  id: "/bill/$outletId/$billId",
  path: "/bill/$outletId/$billId",
  getParentRoute: () => rootRouteImport,
} as any)
const ManageMenuOutletIdRoute = ManageMenuOutletIdRouteImport.update({
  id: "/manage_/menu/$outletId",
  path: "/manage/menu/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const ManageStaffOutletIdRoute = ManageStaffOutletIdRouteImport.update({
  id: "/manage_/staff/$outletId",
  path: "/manage/staff/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const ManageStockOutletIdRoute = ManageStockOutletIdRouteImport.update({
  id: "/manage_/stock/$outletId",
  path: "/manage/stock/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const ManageTablesOutletIdRoute = ManageTablesOutletIdRouteImport.update({
  id: "/manage_/tables/$outletId",
  path: "/manage/tables/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSettingsOutletIdSectionRoute =
  ManageSettingsOutletIdSectionRouteImport.update({
    id: "/manage_/settings/$outletId/$section",
    path: "/manage/settings/$outletId/$section",
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageStaffOutletIdStaffIdRoute =
  ManageStaffOutletIdStaffIdRouteImport.update({
    id: "/manage_/staff/$outletId_/$staffId",
    path: "/manage/staff/$outletId/$staffId",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/alerts": typeof AlertsRoute
  "/bills": typeof BillsRoute
  "/manage": typeof ManageRoute
  "/profile": typeof ProfileRoute
  "/reports": typeof ReportsRoute
  "/outlet/$outletId": typeof OutletOutletIdRoute
  "/pc/$outletId": typeof PcOutletIdRoute
  "/report/$reportId": typeof ReportReportIdRoute
  "/summary/$date": typeof SummaryDateRoute
  "/tables/$outletId": typeof TablesOutletIdRoute
  "/bill/$outletId/$billId": typeof BillOutletIdBillIdRoute
  "/manage/menu/$outletId": typeof ManageMenuOutletIdRoute
  "/manage/staff/$outletId": typeof ManageStaffOutletIdRoute
  "/manage/stock/$outletId": typeof ManageStockOutletIdRoute
  "/manage/tables/$outletId": typeof ManageTablesOutletIdRoute
  "/manage/settings/$outletId/$section": typeof ManageSettingsOutletIdSectionRoute
  "/manage/staff/$outletId/$staffId": typeof ManageStaffOutletIdStaffIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/alerts": typeof AlertsRoute
  "/bills": typeof BillsRoute
  "/manage": typeof ManageRoute
  "/profile": typeof ProfileRoute
  "/reports": typeof ReportsRoute
  "/outlet/$outletId": typeof OutletOutletIdRoute
  "/pc/$outletId": typeof PcOutletIdRoute
  "/report/$reportId": typeof ReportReportIdRoute
  "/summary/$date": typeof SummaryDateRoute
  "/tables/$outletId": typeof TablesOutletIdRoute
  "/bill/$outletId/$billId": typeof BillOutletIdBillIdRoute
  "/manage/menu/$outletId": typeof ManageMenuOutletIdRoute
  "/manage/staff/$outletId": typeof ManageStaffOutletIdRoute
  "/manage/stock/$outletId": typeof ManageStockOutletIdRoute
  "/manage/tables/$outletId": typeof ManageTablesOutletIdRoute
  "/manage/settings/$outletId/$section": typeof ManageSettingsOutletIdSectionRoute
  "/manage/staff/$outletId/$staffId": typeof ManageStaffOutletIdStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/alerts": typeof AlertsRoute
  "/bills": typeof BillsRoute
  "/manage": typeof ManageRoute
  "/profile": typeof ProfileRoute
  "/reports": typeof ReportsRoute
  "/outlet/$outletId": typeof OutletOutletIdRoute
  "/pc/$outletId": typeof PcOutletIdRoute
  "/report/$reportId": typeof ReportReportIdRoute
  "/summary/$date": typeof SummaryDateRoute
  "/tables/$outletId": typeof TablesOutletIdRoute
  "/bill/$outletId/$billId": typeof BillOutletIdBillIdRoute
  "/manage_/menu/$outletId": typeof ManageMenuOutletIdRoute
  "/manage_/staff/$outletId": typeof ManageStaffOutletIdRoute
  "/manage_/stock/$outletId": typeof ManageStockOutletIdRoute
  "/manage_/tables/$outletId": typeof ManageTablesOutletIdRoute
  "/manage_/settings/$outletId/$section": typeof ManageSettingsOutletIdSectionRoute
  "/manage_/staff/$outletId_/$staffId": typeof ManageStaffOutletIdStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/alerts"
    | "/bills"
    | "/manage"
    | "/profile"
    | "/reports"
    | "/outlet/$outletId"
    | "/pc/$outletId"
    | "/report/$reportId"
    | "/summary/$date"
    | "/tables/$outletId"
    | "/bill/$outletId/$billId"
    | "/manage/menu/$outletId"
    | "/manage/staff/$outletId"
    | "/manage/stock/$outletId"
    | "/manage/tables/$outletId"
    | "/manage/settings/$outletId/$section"
    | "/manage/staff/$outletId/$staffId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/alerts"
    | "/bills"
    | "/manage"
    | "/profile"
    | "/reports"
    | "/outlet/$outletId"
    | "/pc/$outletId"
    | "/report/$reportId"
    | "/summary/$date"
    | "/tables/$outletId"
    | "/bill/$outletId/$billId"
    | "/manage/menu/$outletId"
    | "/manage/staff/$outletId"
    | "/manage/stock/$outletId"
    | "/manage/tables/$outletId"
    | "/manage/settings/$outletId/$section"
    | "/manage/staff/$outletId/$staffId"
  id:
    | "__root__"
    | "/"
    | "/alerts"
    | "/bills"
    | "/manage"
    | "/profile"
    | "/reports"
    | "/outlet/$outletId"
    | "/pc/$outletId"
    | "/report/$reportId"
    | "/summary/$date"
    | "/tables/$outletId"
    | "/bill/$outletId/$billId"
    | "/manage_/menu/$outletId"
    | "/manage_/staff/$outletId"
    | "/manage_/stock/$outletId"
    | "/manage_/tables/$outletId"
    | "/manage_/settings/$outletId/$section"
    | "/manage_/staff/$outletId_/$staffId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  BillsRoute: typeof BillsRoute
  ManageRoute: typeof ManageRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  OutletOutletIdRoute: typeof OutletOutletIdRoute
  PcOutletIdRoute: typeof PcOutletIdRoute
  ReportReportIdRoute: typeof ReportReportIdRoute
  SummaryDateRoute: typeof SummaryDateRoute
  TablesOutletIdRoute: typeof TablesOutletIdRoute
  BillOutletIdBillIdRoute: typeof BillOutletIdBillIdRoute
  ManageMenuOutletIdRoute: typeof ManageMenuOutletIdRoute
  ManageStaffOutletIdRoute: typeof ManageStaffOutletIdRoute
  ManageStockOutletIdRoute: typeof ManageStockOutletIdRoute
  ManageTablesOutletIdRoute: typeof ManageTablesOutletIdRoute
  ManageSettingsOutletIdSectionRoute: typeof ManageSettingsOutletIdSectionRoute
  ManageStaffOutletIdStaffIdRoute: typeof ManageStaffOutletIdStaffIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/alerts": {
      id: "/alerts"
      path: "/alerts"
      fullPath: "/alerts"
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bills": {
      id: "/bills"
      path: "/bills"
      fullPath: "/bills"
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/manage": {
      id: "/manage"
      path: "/manage"
      fullPath: "/manage"
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile": {
      id: "/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reports": {
      id: "/reports"
      path: "/reports"
      fullPath: "/reports"
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/outlet/$outletId": {
      id: "/outlet/$outletId"
      path: "/outlet/$outletId"
      fullPath: "/outlet/$outletId"
      preLoaderRoute: typeof OutletOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pc/$outletId": {
      id: "/pc/$outletId"
      path: "/pc/$outletId"
      fullPath: "/pc/$outletId"
      preLoaderRoute: typeof PcOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/report/$reportId": {
      id: "/report/$reportId"
      path: "/report/$reportId"
      fullPath: "/report/$reportId"
      preLoaderRoute: typeof ReportReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/summary/$date": {
      id: "/summary/$date"
      path: "/summary/$date"
      fullPath: "/summary/$date"
      preLoaderRoute: typeof SummaryDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tables/$outletId": {
      id: "/tables/$outletId"
      path: "/tables/$outletId"
      fullPath: "/tables/$outletId"
      preLoaderRoute: typeof TablesOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bill/$outletId/$billId": {
      id: "/bill/$outletId/$billId"
      path: "/bill/$outletId/$billId"
      fullPath: "/bill/$outletId/$billId"
      preLoaderRoute: typeof BillOutletIdBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/manage_/menu/$outletId": {
      id: "/manage_/menu/$outletId"
      path: "/manage/menu/$outletId"
      fullPath: "/manage/menu/$outletId"
      preLoaderRoute: typeof ManageMenuOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/manage_/staff/$outletId": {
      id: "/manage_/staff/$outletId"
      path: "/manage/staff/$outletId"
      fullPath: "/manage/staff/$outletId"
      preLoaderRoute: typeof ManageStaffOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/manage_/stock/$outletId": {
      id: "/manage_/stock/$outletId"
      path: "/manage/stock/$outletId"
      fullPath: "/manage/stock/$outletId"
      preLoaderRoute: typeof ManageStockOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/manage_/tables/$outletId": {
      id: "/manage_/tables/$outletId"
      path: "/manage/tables/$outletId"
      fullPath: "/manage/tables/$outletId"
      preLoaderRoute: typeof ManageTablesOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/manage_/settings/$outletId/$section": {
      id: "/manage_/settings/$outletId/$section"
      path: "/manage/settings/$outletId/$section"
      fullPath: "/manage/settings/$outletId/$section"
      preLoaderRoute: typeof ManageSettingsOutletIdSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/manage_/staff/$outletId_/$staffId": {
      id: "/manage_/staff/$outletId_/$staffId"
      path: "/manage/staff/$outletId/$staffId"
      fullPath: "/manage/staff/$outletId/$staffId"
      preLoaderRoute: typeof ManageStaffOutletIdStaffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  BillsRoute: BillsRoute,
  ManageRoute: ManageRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  OutletOutletIdRoute: OutletOutletIdRoute,
  PcOutletIdRoute: PcOutletIdRoute,
  ReportReportIdRoute: ReportReportIdRoute,
  SummaryDateRoute: SummaryDateRoute,
  TablesOutletIdRoute: TablesOutletIdRoute,
  BillOutletIdBillIdRoute: BillOutletIdBillIdRoute,
  ManageMenuOutletIdRoute: ManageMenuOutletIdRoute,
  ManageStaffOutletIdRoute: ManageStaffOutletIdRoute,
  ManageStockOutletIdRoute: ManageStockOutletIdRoute,
  ManageTablesOutletIdRoute: ManageTablesOutletIdRoute,
  ManageSettingsOutletIdSectionRoute: ManageSettingsOutletIdSectionRoute,
  ManageStaffOutletIdStaffIdRoute: ManageStaffOutletIdStaffIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
