/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AlertsRouteImport } from "./routes/alerts"
import { Route as BillsRouteImport } from "./routes/bills"
import { Route as ManageRouteImport } from "./routes/manage"
import { Route as ProfileRouteImport } from "./routes/profile"
import { Route as ReportsRouteImport } from "./routes/reports"
import { Route as OutletOutletIdRouteImport } from "./routes/outlet.$outletId"
import { Route as PcOutletIdRouteImport } from "./routes/pc.$outletId"
import { Route as TablesOutletIdRouteImport } from "./routes/tables.$outletId"
import { Route as BillOutletIdBillIdRouteImport } from "./routes/bill.$outletId.$billId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: "/alerts",
  path: "/alerts",
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: "/bills",
  path: "/bills",
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: "/manage",
  path: "/manage",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => rootRouteImport,
} as any)
const OutletOutletIdRoute = OutletOutletIdRouteImport.update({
  id: "/outlet/$outletId",
  path: "/outlet/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const PcOutletIdRoute = PcOutletIdRouteImport.update({
  id: "/pc/$outletId",
  path: "/pc/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const TablesOutletIdRoute = TablesOutletIdRouteImport.update({
  id: "/tables/$outletId",
  path: "/tables/$outletId",
  getParentRoute: () => rootRouteImport,
} as any)
const BillOutletIdBillIdRoute = BillOutletIdBillIdRouteImport.update({
  id: "/bill/$outletId/$billId",
  path: "/bill/$outletId/$billId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/alerts": typeof AlertsRoute
  "/bills": typeof BillsRoute
  "/manage": typeof ManageRoute
  "/profile": typeof ProfileRoute
  "/reports": typeof ReportsRoute
  "/outlet/$outletId": typeof OutletOutletIdRoute
  "/pc/$outletId": typeof PcOutletIdRoute
  "/tables/$outletId": typeof TablesOutletIdRoute
  "/bill/$outletId/$billId": typeof BillOutletIdBillIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/alerts": typeof AlertsRoute
  "/bills": typeof BillsRoute
  "/manage": typeof ManageRoute
  "/profile": typeof ProfileRoute
  "/reports": typeof ReportsRoute
  "/outlet/$outletId": typeof OutletOutletIdRoute
  "/pc/$outletId": typeof PcOutletIdRoute
  "/tables/$outletId": typeof TablesOutletIdRoute
  "/bill/$outletId/$billId": typeof BillOutletIdBillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/alerts": typeof AlertsRoute
  "/bills": typeof BillsRoute
  "/manage": typeof ManageRoute
  "/profile": typeof ProfileRoute
  "/reports": typeof ReportsRoute
  "/outlet/$outletId": typeof OutletOutletIdRoute
  "/pc/$outletId": typeof PcOutletIdRoute
  "/tables/$outletId": typeof TablesOutletIdRoute
  "/bill/$outletId/$billId": typeof BillOutletIdBillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/alerts"
    | "/bills"
    | "/manage"
    | "/profile"
    | "/reports"
    | "/outlet/$outletId"
    | "/pc/$outletId"
    | "/tables/$outletId"
    | "/bill/$outletId/$billId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/alerts"
    | "/bills"
    | "/manage"
    | "/profile"
    | "/reports"
    | "/outlet/$outletId"
    | "/pc/$outletId"
    | "/tables/$outletId"
    | "/bill/$outletId/$billId"
  id:
    | "__root__"
    | "/"
    | "/alerts"
    | "/bills"
    | "/manage"
    | "/profile"
    | "/reports"
    | "/outlet/$outletId"
    | "/pc/$outletId"
    | "/tables/$outletId"
    | "/bill/$outletId/$billId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  BillsRoute: typeof BillsRoute
  ManageRoute: typeof ManageRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  OutletOutletIdRoute: typeof OutletOutletIdRoute
  PcOutletIdRoute: typeof PcOutletIdRoute
  TablesOutletIdRoute: typeof TablesOutletIdRoute
  BillOutletIdBillIdRoute: typeof BillOutletIdBillIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/alerts": {
      id: "/alerts"
      path: "/alerts"
      fullPath: "/alerts"
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bills": {
      id: "/bills"
      path: "/bills"
      fullPath: "/bills"
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/manage": {
      id: "/manage"
      path: "/manage"
      fullPath: "/manage"
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile": {
      id: "/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reports": {
      id: "/reports"
      path: "/reports"
      fullPath: "/reports"
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/outlet/$outletId": {
      id: "/outlet/$outletId"
      path: "/outlet/$outletId"
      fullPath: "/outlet/$outletId"
      preLoaderRoute: typeof OutletOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pc/$outletId": {
      id: "/pc/$outletId"
      path: "/pc/$outletId"
      fullPath: "/pc/$outletId"
      preLoaderRoute: typeof PcOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tables/$outletId": {
      id: "/tables/$outletId"
      path: "/tables/$outletId"
      fullPath: "/tables/$outletId"
      preLoaderRoute: typeof TablesOutletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bill/$outletId/$billId": {
      id: "/bill/$outletId/$billId"
      path: "/bill/$outletId/$billId"
      fullPath: "/bill/$outletId/$billId"
      preLoaderRoute: typeof BillOutletIdBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  BillsRoute: BillsRoute,
  ManageRoute: ManageRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  OutletOutletIdRoute: OutletOutletIdRoute,
  PcOutletIdRoute: PcOutletIdRoute,
  TablesOutletIdRoute: TablesOutletIdRoute,
  BillOutletIdBillIdRoute: BillOutletIdBillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
